version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/static-public-share
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/app_start_service.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/app_stop_service.sh
      timeout: 30
      runas: root
